config/routes.rb
Rails.application.routes.draw do
  get 'experiments/page1'

  get 'experiments/page2'

  get 'experiments/page3'

  get 'pages/batman'

  get 'pages/superman'

  get 'pages/batmanvssuperman'

  post 'pages/voto_superman'

  post 'pages/voto_batman'

  root 'pages#batmanvssuperman'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/votosuperman.rb
class Votosuperman < ApplicationRecord
end

app/models/votsbatman.rb
class Votsbatman < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  def page1

  end

  def page2
    render :layout => '_bootstrap'
  end

  def page3
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :verify_authenticity_token
  def batman
  end

  def superman
  end

  def batmanvssuperman
    @count1 = Votosuperman.count
    @count2 = Votsbatman.count
  end

  def voto_superman
    Votosuperman.new(nombre: params[:nombre], email: params[:email]).save
    redirect_to pages_batmanvssuperman_path, notice: 'el voto para superman se hizo correctamente'
  end

  def voto_batman
    Votsbatman.new(nombre: params[:nombre], email: params[:email]).save
    redirect_to pages_batmanvssuperman_path, notice: 'el voto para batman se hizo correctamente'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/experiments/page1.html.erb
esta imagen es de batman
<%= image_tag(asset_path('batman.png'))  %>

app/views/experiments/page2.html.erb
<h1>Experiments#page2</h1>
<p>Find me in app/views/experiments/page2.html.erb</p>

app/views/experiments/page3.html.erb
<h1>Experiments#page3</h1>
<p>Find me in app/views/experiments/page3.html.erb</p>

app/views/layouts/_bootstrap.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Superheroes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Superheroes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/bootsrap.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Superheroes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/batman.html.erb
<h1>I'm Batman</h1>
<script>
   $.backstretch("https://mi-od-live-s.legocdn.com/r/www/r/catalogs/-/media/catalogs/characters/dimensions/mugshot%20december%202016/71200_71170-71174_1to1_mf_mugshot_batman_336.png?l.r2=-1434101541");
</script>

app/views/pages/batmanvssuperman.html.erb
<script>
   $.backstretch("http://www.gamedots.mx/media/gd/animated-gifs-of-fighting-game-backgrounds-8.gif");
</script>

  <a href="<%= pages_superman_url %>"> <img class="tam1" src="https://lc-www-live-s.legocdn.com/r/www/r/catalogs/-/media/catalogs/characters/dimensions/mugshots/71236_1to1_mf_mugshot_superman_168.png?l.r2=1891380887" alt=""></a>
  <a href="<%= pages_batman_url %>">  <img class="tam2" src="https://mi-od-live-s.legocdn.com/r/www/r/catalogs/-/media/catalogs/characters/dimensions/mugshot%20december%202016/71200_71170-71174_1to1_mf_mugshot_batman_336.png?l.r2=-1434101541" alt=""> </a>


<div class="container">
  <div class="col-md-6 align">
    <form action="<%= pages_voto_superman_path %>" method="post">
      <input name="name" value="" placeholder="Name">
      <input name="email" value="" placeholder="Email"><br>
      <input type="submit" name="enviar" value="voto por superman">
    </form>
    <h2 class="font2"><%= @count1 %> votos para superman</h2>
  </div>
  <div class="col-md-6 align">
    <form action="<%= pages_voto_batman_path %>" method="post">
      <input name="name" value="" placeholder="Name">
      <input name="email" value="" placeholder="Email"> <br>
      <input type="submit" name="enviar" value="voto por batman">
    </form>
    <h2 class="font2"><%= @count2 %> votos para batman</h2>
  </div>
</div>
    <h2 class= "font1" ><%= flash[:notice]%> </h2>

app/views/pages/superman.html.erb
<h1>This looks like a job for Superman</h1>
<script>
   $.backstretch("http://www.pelijuegos.com/wp-content/uploads/2014/04/superman-lego-250x294.jpg");
</script>